orf/gping

setup.py
Pip doesn't seem to install the requirements just from `requirements` in `setup.py`. This makes it so that pip will install them when `gping` is installed.
=> Add install requirements

gping/pinger.py
It was not possible to start gping in simulation mode.
Your linux regexp didn't match lines containing time without the dot for example here:
64 bytes from lhr14s23-in-f36.1e100.net (216.58.210.36): icmp_seq=2 ttl=52 time=83.6 ms
64 bytes from lhr14s23-in-f36.1e100.net (216.58.210.36): icmp_seq=3 ttl=52 time=133 ms
It was unable to match second line (fixes #2 )
I don't know why it was so complicated too. I fixed this issue and simplified the regexp.
=> Fix simulation mode and linux regexp.

gping/pinger.py
Add a new `_darwin` runner, fixing the regular expression
so it works on Darin (tested on El Capitan)
Also check for 'Request timeout' and return -1.0 if that happens.
=> Add OS X (Darwin) support

gping/pinger.py
Removing unused `Bitmap.__getitem__`, which contains unresolved references to `idx`.
It appears this method once had good intentions, but the `Bitmap` abstraction is seldom used throughout the code (the `_bitmap` member is being accessed directly). It would probably be a good idea to make full use of `Bitmap`, but I'll leave that for another PR.
=> Remove unused Bitmap.__getitem__

gping/pinger.py
this error was caused by a zero division error
Also, if the ping was always zero the bar would be
the entire size, now it will only be 1 high
=> If the ping was 0ms it would error

gping/pinger.py
Hello,
I have been using Gping for a while now and have always loved it. I do well with visualizations and this creates a really good visualization of a network connection with very little overhead. Which I like :)
However, I have always noticed that on my computers (all macs) the graphs would print one after another and create huge amounts of text in my terminal window. I finally bit the bullet and decided to dive in and figure out how to fix it.
I have pushed a very minimal changeset, outlined below:
- Populate initial Canvas object with one fewer line. When the canvas lines were joined there was an extra newline being printed which over time generates a huge amount of blank space in the terminal.  
- Added code to generate a blank “graph” prior to the first graph being drawn. This …
=> Small bug fixes for Darwin (MacOS)

readme.md
Thanks for making gping. I've fixed up the link to the snapcraft build page from the badge.
=> Fix snapcraft badge link

gping/pinger.py
Fixes #48. This patch draw the statistics from top to bottom and ensure nothing is drawn outside the window (tested with a minimum of 20x5).
=> Fix the crash when the window is resized too small

src/main.rs
Allows the user to specify a number for the amount of pings to store and display. Defaults to the original 100.
Might wanna add some kinda dumping mechanism in the future.
Signed-off-by: Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>
=> Allow users to specify custom buffer sizes.

src/main.rs, src/ringbuffer.rs
This introduces a data structure that replaces `Vec<(f64, f64)>` so that it does not perform a shift left at every push when its at full capacity. This should introduce performance benefits when the buffer is large enough. Additionally, this data structure performs better the larger the buffer size.
Signed-off-by: Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>
=> Use ringbuffer instead of using memcpy to shift element at EVERY PUSH

readme.md
This will automatically run `brew tap orf/brew`, and is more convenient.
=> Simplify homebrew installtion command

src/main.rs
The issue brought up in #115 is a result of the generated labels having too large of an increment and accumulating well past the maximum value. 
This PR calculates labels more true to the min/max values by chunking the max - min difference into the same 7 chunks that are used for the labels. There's still a chance for misalignment on either sides, but this is much closer.
=> Fix chart label to better align with results min/max values

readme.md, src/main.rs
Adding a flag to force IPv4/IPv6:
```
$ cargo run -- icanhazip.com
icanhazip.com (2604:1380:45f1:3c00::1)
...
```
```
$ cargo run -- icanhazip.com -6
icanhazip.com (2604:1380:45f1:3c00::1)
...
```
```
$ cargo run -- icanhazip.com -4
icanhazip.com (147.75.47.199)
...
```
If an A or AAAA record isn't found:
```
$ cargo run -- github.com -6
Error: Could not resolve 'github.com' to IPv6
```
=> Adding flags to force host resolution to IPv4 or IPv6

readme.md
Hey,
I'm an [Arch Linux](https://aur.archlinux.org) package [maintainer](https://github.com/orhun/PKGBUILDs). I'm submitting this PR to let you know that I created the following package for the installation of `gping` on Arch Linux:
* [gping](https://aur.archlinux.org/packages/gping/) (builds from source)
I also updated readme.md about installation from AUR. (c679bf3)
Regards,
orhun.
=> docs: add Arch Linux installation instructions

readme.md
`gping` is now available in Arch's Community repository. [link](https://archlinux.org/packages/community/x86_64/gping/).
=> Update install guide for Arch Linux

readme.md, src/main.rs, src/plot_data.rs
Added the --simple-graphics/-s flag to use dot characters instead of braille for compatibility.
This is basically the same as how it's done in the tui-rs demos (https://github.com/fdehau/tui-rs/blob/master/examples/crossterm_demo.rs) but inverted to make the default more clear.
Solves #122
=> Added flag to use simpler dot-based graphics

src/main.rs, src/plot_data.rs
I fixed the issue #127.
Now timeouts get displayed correctly (no new values in graph and min value).
I also added a field where the number of timeouts are counted.
I would be happy if my fix gets integrated.
=> (fix) display timeouts correctly see #127

readme.md
Since v0.1.7, gping has been available on [MacPorts](https://ports.macports.org/). Inspired by https://github.com/orf/gping/pull/141, I thought I'd document this.
You can find the project page [here](https://ports.macports.org/port/gping/), and it can be installed by running the following on macOS:
```
sudo port install gping
```
Pre-built binaries are available all the way from macOS 11 arm to Mavericks. I also added the [repology](https://repology.org/) badge and Homebrew page for this project.
Finally, it goes without saying, but thanks @orf for maintaining this really useful tool. Your updates and bugfixes are greatly appreciated.
=> Add MacPorts Documentation + Repology

pinger/src/lib.rs
Support was broken for NixOS - and it was needed to add `os_info::Type::NixOS` to a match-clause in `pinger::ping_with_interval(..)`
=> Add NixOS as supported type

gping/src/main.rs
When `gping` used in tight spaces (e.g. in a small pane of `tmux`) then having that default `1` as vertical margin could be quite a waste of screen estate.   This PR adds support to override both the vertical and horizontal margins, whilst keeping it backward compatible, i.e. the vertical defaults to `1` and the horizontal defaults to `0`.
=> Add customisable vertical and horizontal margins

Cargo.lock, gping/Cargo.toml, gping/src/colors.rs, gping/src/main.rs
This PR implements customisable colour support for `gping` via the `-c` / `--color` flag.
If no value is defined then `gping` behaves as it did before.
If any number of flags are defined then their values are matched against the _hosts or commands_ arguments.  If less colours have been specified than _hosts or commands_ it enumerates the colour values by index (as before).
Colours can be defined by names (the ones which are supported by `tui`) or by hexadecimal RGB codes.  
This feature is also trying to be clever about the already used colours, however `tui::style::Color`s are not represented the same way so this _smart_ feature likely ends up being _dumb_ when it comes to detect colours which have not already being specified by the user.  (The user is allowed to define duplicates, …
=> Add support for custom colors to be defined by either name or code

gping/src/lib.rs, gping/src/main.rs, gping/src/region_map.rs
This will allow AWS region to be tested without tracking actual long host names. The lookup can be on city name or region name.
=> short cut for testing AWS regions

gping/src/main.rs, readme.md
This change clears the GUI from your terminal history, assuming that you don't want to view the graph after you close it. Here's an example of the new and old behaviour. 
Also fixed a small clippy lint.
=> clear graph from terminal history

gping/src/plot_data.rs
This PR did three change:
1. Moved the `sorted_by` operation after the map, saving space in the intermediate vector that `sorted_by` builds.
2. Replaced a `fold` operation with a straightforward `sum`.
3. Utilized `zip` to calculate `jtr`, reducing the need for an additional `get` step.
=> Refactor: Reduce iter complexity in `header_stats`

Cargo.lock, gping/Cargo.toml, gping/src/colors.rs, gping/src/main.rs
Fixes https://github.com/orf/gping/issues/331
Removes `try_color_from_string` since this has been implemented in the Ratatui style mod.
Left one TODO for future possible changes to the naming convention.
Update the long help text of the color option.
=> clean-up(color.rs): remove `try_color_from_string`

gping/src/main.rs
By leveraging the `minmax` method provided by `itertools`, we were
able to eliminate the need for one iterator clone operation in the
`y_axis_bounds` function. This refactor enhances the efficiency and
readability of the codebase.
In #323, I made some mistakes in the `NoElements` branch and minmax
won't work on f64::NAN. This commit fixes the issue.
ref https://github.com/orf/gping/pull/323
=> Refactor: Reduce iterator cloning in y_axis_bounds

readme.md
- clap_lex clap anstyle-query anstyle anstream ratatui =< 1.63.0
- time =< 1.67.0
=> readme: Raise minimum rustc spec to 1.67.0 as required by time package

gping/src/main.rs
fixes #394
the .as_ref() call was breaking the typing somewhere, removing it seems to have fixed the issue. i am not familiar enough with the codebase to know if the actual issue is that &Vec<Constraint> should implement Into<Constraint>, but this seems to work
=> fixed reference typing issue

readme.md
- Adding `--rm` so no container is kept after the end of execution (on `docker ps -a`)
- Adding `-ti` so `q` works to exit
- Adding `--network host` so uses the same network as the host
- Bumped version to 1.15.1
=> Better docker examples

Cargo.lock
Update libc to v0.2.155 to support loongarch64.
Release notes: https://github.com/rust-lang/libc/releases.
=> Update Cargo.lock: fix build on loongarch64

gping/src/main.rs
`ratatui` `0.26.0` has a breaking change that affects this crate:
https://github.com/ratatui-org/ratatui/blob/60bd7f48140023483a5281365dc4561011050dae/BREAKING-CHANGES.md?plain=1#L23
This PR specifies `Flow::Legacy` to the `chunks` `Layout` to avoid the behaviour mentioned in #460 that is a result of this.
=> Specify `Flex::Legacy` for `Layout`. #460

readme.md
Hello!
This PR adds to the documentation installation method using [gah](https://github.com/marverix/gah):
> gah is an GitHub Releases app installer, that DOES NOT REQUIRE SUDO! It is a simple bash script that downloads the latest release of an app from GitHub and installs it in ~/.local/bin. It is designed to be used with apps that are distributed as a single binary file.
I also fixed indents for other installation code blocks :)
=> docs: Add installation method with gah

pinger/Cargo.toml
=> chore: update repository link
